# Site settings
author: William Taylor
description: "Technology Associate @ Morgan Stanley"
url: "/online-cover"
github_username:  william-taylor
facebook_username: william.taylor.1707
twitter_username: wiltaylo
linkedin_username: william-sam-taylor
cv_url: https://cv.williamsamtaylor.co.uk

# Image settings
avatar: yes
avatar_img_path: "images/profile.jpeg"
front_img: yes
front_img_path: "images/london2.jpg"
favicon_img: yes
favicon_img_path: "images/icon.png"

# Build settings
markdown: kramdown
permalink: pretty
