# Site settings
author: William Taylor
description: "Technology Associate at Morgan Stanley working on multiple greenfield projects and key renovation work on several critical applications."
url: ''
github_username:  william-taylor
twitter_username: wiltaylo
linkedin_username: william-sam-taylor
cv_url: https://cv.williamsamtaylor.co.uk
analytics: UA-96533413-5

# Image settings
avatar: yes
avatar_img_path: "images/profile.png"
front_img: yes
front_img_path: "images/shard.jpg"
favicon_img: yes
favicon_img_path: "images/icon.png"

# Build settings
markdown: kramdown
permalink: pretty
