# Site settings
author: William Taylor
description: "Technology Associate at Morgan Stanley working on a greenfield project and major renovation of an existing system."
url: ''
github_username:  william-taylor
#facebook_username: william.taylor.1707
twitter_username: wiltaylo
linkedin_username: william-sam-taylor
cv_url: https://cv.williamsamtaylor.co.uk
analytics: UA-96533413-5

# Image settings
avatar: yes
avatar_img_path: "images/profile.jpeg"
front_img: yes
front_img_path: "images/london.jpg"
favicon_img: yes
favicon_img_path: "images/icon.png"

# Build settings
markdown: kramdown
permalink: pretty
